# Generated by Django 5.0.7 on 2024-08-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faroldesantamartaapp', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
